[package]
name = "ctl"
version = "0.1.0"
edition = "2018"
authors = ["The TiKV Authors"]

[dependencies]
clap = { version = "4.0.17", features = ["derive", "cargo"] }
raft-engine = { path = "..", features = ["scripting", "internals"] }
